_target_: dos.trainer.Trainer # Class Name

train_dataset:
  _target_: dos.datasets.ImageDataset       # Class Name
  root_dir: /scratch/shared/beegfs/oishideb/cow  # sample 1
  # root_dir: /work/oishideb/cow_sample_2  # sample 2
  # root_dir: /work/oishideb/cow_dataset/cow_dataset # 9 images
  # root_dir: /scratch/shared/beegfs/tomj/projects/articulator/datasets/synth_animals/cow-rd-articulator-v1.0  # Corrupted dataset
  attributes:
    - name: image
      suffix: _rgb.png
    - name: mask
      suffix: _mask.png
    - name: background
      suffix: _background.png
    - name: camera_matrix
      suffix: _camera.txt

model:
  _target_: dos.models.articulator.Articulator 
  bones_predictor:
    _target_: dos.components.skinning.bones_estimation.BonesEstimator
    num_body_bones: 8
    num_leg_bones: 3
    body_bones_type: z_minmax_y+
    temperature: 0.05

  path_to_save_images: /scratch/shared/beegfs/dos/articulator/cow
  num_pose: 10
  num_sample_bone_line: 4  # 
  mode_kps_selection: "kps_fr_sample_on_bone_line" # Options are "kps_fr_sample_on_bone_line" OR "kps_fr_sample_farthest_points"
  shape_template_path: /scratch/shared/beegfs/tomj/projects/articulator/data/synth_animals/shape_templates/cow_female-rd/Cow-OBJ-v01/Cow_Highpoly.obj
  fit_shape_template_inside_unit_cube: True
  enable_texture_predictor: False
  view_option: "multi_view_azimu" # Options are "multi_view_azimu"; "multi_view_rand"; "single_view"
  random_camera_radius: 2.5
  debug_mode: True # IN DEBUG MODE, THIS WILL SWITCH OFF THE LOADING TO FUSE'S STABLE DIFFUSION MODEL
  
  articulation_predictor:
    _target_: dos.predictors.articulation_predictor.ArticulationPredictor  # Class Name
    size_dataset: 49
    num_bones: 20
    
  renderer:   # variable Name
    _target_: dos.modules.renderer.Renderer # Class Name
    cam_pos_z_offset: 0.0
    fov: 28.84 # blender 70 mm focal length, 36 mm sensor width

  diffusion_Text_to_Target_Img:  # variable Name
    _target_: dos.components.diffusion_model_text_to_image.diffusion_sds.DiffusionForTargetImg # Class Name
     # cache_dir:
    output_dir: "sd_sds_output"
    init_image_path: /users/oishideb/laam/dos/examples/data/cow.png
    vis_name: cow-sds_latent-l2_image-600-lr1e-1.jpg
    # prompts: 'A photograph of a single cow running very fast, back view.' #.The photo should have a grey background.' # DOS-1338  opti multi_view_azimu, GS20, Num_Infe50
    prompts_source: '' #.The photo should have a grey background.' # DOS-1339  opti multi_view_azimu, GS20, Num_Infe50
    negative_prompts: 'front view, side view, tail' #  , cartoon, dead, shadow, reflection'     # the string shouldn't be in a square brackets ['']
    prompts: 'A photograph of a cow running very fast, back view. All four legs should be visible. No cow tail'
    mode: sds_latent-l2_image # Options are sds_image OR sds_latent-l2_image #
    lr: 0.1  # For DeepFloyd
    lr_l2: 1e4  # For SD+SDS
    seed: 2
    num_inference_steps: 50
    guidance_scale: 20
    dds: False
    select_diffusion_option: 'sd' # Options are sd, sd_XL, df, sd_dds_loss  # by default is sds loss
    image_fr_path: False
  
#path_to_save_horse_img: /users/oishideb/dos_output_files/horse/15_Sept
path_to_save_img_per_iteration: /scratch/shared/beegfs/dos/articulator/cow/all_iteration_Train
checkpoint_root_dir: /scratch/shared/beegfs/dos/articulator/cow/checkpoints
experiment_name: articulator-dev-0.1
save_each_iteration: True 
evaluate_the_model: False

device: cuda:0

# resume: True

learning_rate: 1e-6

# for debugging
num_iterations: 150
num_vis_iterations: 1
num_eval_iterations: 10
save_checkpoint_freq: 50
num_workers: 0
batch_size: 1
